name: Pull request Pipeline

on:
  pull_request:
    branches: 
      - main
      - develop

jobs:
  build:
    name: PBI Fair project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install Dependencies
        run: yarn

      - name: Build
        run: yarn build
